apiVersion: v2
name: tooljet
type: application
description: ToolJet is an open-source low-code framework to build and deploy internal tools quickly without much effort from the engineering teams.
maintainers:
- name: akshay-sasidharan
  email: akshay@tooljet.io

dependencies:
- condition: postgresql.enabled
  name: postgresql
  version: "11.6.19"
  repository: "https://charts.bitnami.com/bitnami"
- condition: redis.enabled
  name: redis
  version: "16.13.2"
  repository: "https://charts.bitnami.com/bitnami"  

<<<<<<< Updated upstream:Chart.yaml
version: v2.25.0
appVersion: "v2.25.0"
=======
version: 2.6.2
appVersion: "v1.21.5"
>>>>>>> Stashed changes:charts/tooljet/Chart.yaml
