{{- with .Values.apps.tooljet.hpa }}
{{- if .enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tooljet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tooljet
  minReplicas: {{ .min }}
  maxReplicas: {{ .max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: {{ .threshhold.cpu }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .threshhold.ram }}
{{- end }}
{{- end }}
