{{- if and .Values.ingress.enabled (eq .Values.ingress.type "nginx") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tooljet.fullname" . }}-nginx
  labels:
    {{- include "tooljet.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tooljet.fullname" . }}
                port:
                  number: {{ .Values.apps.tooljet.service.port }}
{{- end }}
