apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apps.tooljet.secret.name }}
  labels:
    {{- include "tooljet.labels" . | nindent 4 }}
    {{- include "tooljet.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.external_postgresql.enabled }}
  PG_HOST: {{ include "tooljet.postgresql.host" . | b64enc | quote }}
  PG_PORT: {{ include "tooljet.postgresql.port" . | b64enc | quote }}
  PG_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  PG_PASS: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  {{- else }}
  PG_HOST: {{ .Values.external_postgresql.PG_HOST | b64enc | quote }}
  PG_PORT: {{ .Values.external_postgresql.PG_PORT | b64enc | quote }}
  PG_USER: {{ .Values.external_postgresql.PG_USER | b64enc | quote }}
  PG_PASS: {{ .Values.external_postgresql.PG_PASS | b64enc | quote }}
  {{- end }}
  PG_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}
  LOCKBOX_MASTER_KEY: {{ .Values.apps.tooljet.secret.data.lockbox_key | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.apps.tooljet.secret.data.secret_key_base | b64enc | quote }}
  {{- if .Values.tooljetdb_external_postgresql.enabled }}
  TOOLJET_DB_HOST: {{ .Values.tooljetdb_external_postgresql.TOOLJET_DB_HOST | b64enc | quote }}
  TOOLJET_DB_USER: {{ .Values.tooljetdb_external_postgresql.TOOLJET_DB_USER | b64enc | quote }}
  TOOLJET_DB_PASS: {{ .Values.tooljetdb_external_postgresql.TOOLJET_DB_PASS | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.auth.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
---
# New PostgREST secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tooljet.fullname" . }}-postgrest
  labels:
    {{- include "tooljet.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
type: Opaque
data:
  PGRST_DB_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.auth.username .Values.postgresql.auth.postgresPassword (include "tooljet.postgresql.host" .) (include "tooljet.postgresql.port" .) (include "tooljet.postgresql.database" .) | b64enc | quote }}
  PGRST_JWT_SECRET: {{ .Values.env.PGRST_JWT_SECRET | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tooljet.fullname" . }}-redis
  labels:
    {{- include "tooljet.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.auth.enabled }}
  password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}