{{- if .Values.plaintextSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tooljet-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.plaintextSecrets.secrets}}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}