apiVersion: v1
kind: Service
metadata:
  name: {{ include "tooljet.fullname" . }}
  labels:
    {{- include "tooljet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apps.tooljet.service.type }}
  ports:
    - port: {{ .Values.apps.tooljet.service.port | default 3000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tooljet.selectorLabels" . | nindent 4 }}