apiVersion: v1
kind: Service
metadata:
  name: {{ include "tooljet.fullname" . }}-postgrest
  labels:
    {{- include "tooljet-postgrest.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "tooljet-postgrest.selectorLabels" . | nindent 4 }}
  type: {{ .Values.postgrest.service.type }}
  ports:
    - name: http
      port: {{ .Values.postgrest.service.port }}
      targetPort: {{ .Values.postgrest.containerPort }}
      protocol: TCP
      {{- if and (eq .Values.postgrest.service.type "NodePort") .Values.postgrest.service.nodePort }}
      nodePort: {{ .Values.postgrest.service.nodePort }}
      {{- end }}
