apiVersion: v1
kind: Service
metadata:
  name: {{ include "tooljet.fullname" . }}-postgrest
  labels:
    {{- include "tooljet.labels" . | nindent 4 }}
    app.kubernetes.io/component: tooljet-postgrest
    app.kubernetes.io/instance: tooljet-postgrest
    app.kubernetes.io/name: tooljet-postgrest
spec:
  selector:
    {{- include "tooljet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tooljet-postgrest
    app.kubernetes.io/instance: tooljet-postgrest
    app.kubernetes.io/name: tooljet-postgrest
  type: {{ .Values.postgrest.service.type }}
  ports:
    - name: http
      port: {{ .Values.postgrest.service.port }}
      targetPort: {{ .Values.postgrest.containerPort }}
      protocol: TCP
      {{- if and (eq .Values.postgrest.service.type "NodePort") .Values.postgrest.service.nodePort }}
      nodePort: {{ .Values.postgrest.service.nodePort }}
      {{- end }}
