apiVersion: v1
kind: Service
metadata:
  name: tooljet-postgrest
  labels:
    name: tooljet-postgrest  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: tooljet-postgrest