apiVersion: v1
kind: Service
metadata:
  name: {{ include "tooljet.fullname" . }}-postgrest
  labels:
    {{- include "tooljet.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Release.Name }}-postgrest
    app.kubernetes.io/instance: {{ .Release.Name }}-postgrest
    app.kubernetes.io/name: {{ .Release.Name }}-postgrest
spec:
  selector:
    app.kubernetes.io/component: {{ .Release.Name }}-postgrest
    app.kubernetes.io/instance: {{ .Release.Name }}-postgrest
    app.kubernetes.io/name: {{ .Release.Name }}-postgrest
  type: {{ .Values.postgrest.service.type }}
  ports:
    - name: http
      port: {{ .Values.postgrest.service.port }}
      targetPort: {{ .Values.postgrest.containerPort }}
      protocol: TCP
      {{- if and (eq .Values.postgrest.service.type "NodePort") .Values.postgrest.service.nodePort }}
      nodePort: {{ .Values.postgrest.service.nodePort }}
      {{- end }}
