{{- if .Values.apps.tooljet.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tooljet.serviceAccountName" . }}
  labels:
    {{- include "tooljet.labels" . | nindent 4 }}
  {{- if .Values.apps.tooljet.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.apps.tooljet.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
