apiVersion: v1
kind: Service
metadata:
  name: tooljet-postgrest-service
  labels:
    name: tooljet-postgrest
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: tooljet-postgrest
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.postgrest.port }}
      targetPort: {{ .Values.postgrest.targetPort }}
      protocol: TCP