apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooljet-worker-deployment
  labels:
    app: tooljet-worker  # Corrected label format
    component: worker    # You can add more labels as needed
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.apps.tooljet.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: tooljet-worker  # Updated to match the label key
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: tooljet-worker   # Updated to match the label key
        component: worker     # Updated for consistency
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.apps.tooljet.deployment.image.repository }}:{{ .Values.apps.tooljet.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.apps.tooljet.deployment.image.pullPolicy }}
          args: ["npm", "run", "worker:prod"]
          ports:
            - name: http
              containerPort: {{ .Values.apps.tooljet.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.apps.tooljet.deployment.resources | nindent 12 }}
          env:
            - name: TOOLJET_HOST
              value: {{ .Values.env.TOOLJET_HOST | quote }}
            {{- if not .Values.external_postgresql.enabled }}
            - name: PG_HOST
              value: {{ include "tooljet.postgresql.host" . | quote }}
            - name: PG_PORT
              value: {{ include "tooljet.postgresql.port" . | quote }}
            - name: PG_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "tooljet.postgresql.secretName" . }}
                  key: postgres-password
            {{- else }}
            - name: PG_HOST
              value: {{ .Values.external_postgresql.PG_HOST | quote }}
            - name: PG_PORT
              value: {{ .Values.external_postgresql.PG_PORT | quote }}
            - name: PG_USER
              value: {{ .Values.external_postgresql.PG_USER | quote }}
            - name: PG_PASS
              value: {{ .Values.external_postgresql.PG_PASS | quote }}
            - name: PG_DB
              value: {{ .Values.external_postgresql.PG_DB | quote }}
            {{- end }}
            - name: ENABLE_TOOLJET_DB
              value: {{ .Values.env.ENABLE_TOOLJET_DB | quote }}
            {{- if .Values.tooljetdb_external_postgresql.enabled }}
            - name: TOOLJET_DB_HOST
              value: {{ .Values.tooljetdb_external_postgresql.TOOLJET_DB_HOST | quote }}
            - name: TOOLJET_DB_USER
              value: {{ .Values.tooljetdb_external_postgresql.TOOLJET_DB_USER | quote }}
            - name: TOOLJET_DB_PASS
              value: {{ .Values.tooljetdb_external_postgresql.TOOLJET_DB_PASS | quote }}
            - name: TOOLJET_DB
              value: {{ .Values.tooljetdb_external_postgresql.TOOLJET_DB | quote }}
            {{- else }}
            - name: TOOLJET_DB_HOST
              value: {{ .Values.env.TOOLJET_DB_HOST | quote }}
            - name: TOOLJET_DB_USER
              value: {{ .Values.env.TOOLJET_DB_USER | quote }}
            - name: TOOLJET_DB_PASS
              value: {{ .Values.env.TOOLJET_DB_PASS | quote }}
            - name: TOOLJET_DB
              value: {{ .Values.env.TOOLJET_DB | quote }}
            {{- end }}
            - name: ENABLE_WORKFLOW_SCHEDULING
              value: {{ .Values.workflow_env.ENABLE_WORKFLOW_SCHEDULING | quote }}
            - name: TEMPORAL_SERVER_ADDRESS
              value: {{ .Values.workflow_env.TEMPORAL_SERVER_ADDRESS }}
            - name: TEMPORAL_TASK_QUEUE_NAME_FOR_WORKFLOWS
              value: {{ .Values.workflow_env.TEMPORAL_TASK_QUEUE_NAME_FOR_WORKFLOWS }}
            - name: TOOLJET_WORKFLOWS_TEMPORAL_NAMESPACE
              value: {{ .Values.workflow_env.TOOLJET_WORKFLOWS_TEMPORAL_NAMESPACE }}
            - name: WORKER
              value: {{ .Values.workflow_env.WORKER | quote }}
            - name: PGRST_HOST
              value: {{ .Values.env.PGRST_HOST }}
            - name: PGRST_JWT_SECRET
              value: {{ .Values.env.PGRST_JWT_SECRET | quote }}
            - name: REDIS_HOST
              value: {{ .Values.redis_pod.REDIS_HOST | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis_pod.REDIS_PORT | quote }}
            - name: REDIS_USER
              value: {{ .Values.redis_pod.REDIS_USER | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "tooljet.fullname" . }}-redis
                  key: password
            - name: LOCKBOX_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apps.tooljet.secret.name }}
                  key: LOCKBOX_MASTER_KEY
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apps.tooljet.secret.name }}
                  key: SECRET_KEY_BASE
          envFrom:
            - secretRef:
                name: {{ .Values.apps.tooljet.secret.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
