apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tooljet.fullname" . }}-nginx-config-template
  labels:
    app: {{ template "tooljet.fullname" . }}
    chart: {{ template "tooljet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  nginx.conf.template: "
  events
  {
    worker_connections 1024;
  }
  http
  {
    server
    {

      location /
      {
        root /var/www;
        try_files $uri $uri/ /index.html @proxy;
        error_page 405 @proxy;
      }

      location /api/
      {
        try_files /_bypass_to_proxy @proxy;
      }

      location /ws
      {
        proxy_pass http://{{ template "tooljet.fullname" . }}:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
      }

      location /yjs
      {
        proxy_pass http://{{ template "tooljet.fullname" . }}:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
      }

      location @proxy {
        proxy_pass http://{{ template "tooljet.fullname" . }}:3000;
        proxy_redirect off;
        proxy_set_header Host $host;
      }
    }

    server
    {
      listen 80;

      location /
      {
        root /var/www;
        try_files $uri $uri/ /index.html @proxy;
        error_page 405 @proxy;
      }

      location /api/
      {
        try_files /_bypass_to_proxy @proxy;
      }

      location /ws
      {
        proxy_pass http://{{ template "tooljet.fullname" . }}:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
      }

      location /yjs
      {
        proxy_pass http://{{ template "tooljet.fullname" . }}:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
      }

      location @proxy {
        proxy_pass http://{{ template "tooljet.fullname" . }}:3000;
        proxy_redirect off;
        proxy_set_header Host $host;
      }
    }

    server
    {
      listen 127.0.0.1:8999;
      client_body_buffer_size 128k;
      client_max_body_size 128k;
    }
}"